# Generated by Django 4.2.1 on 2023-06-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customuser_code_codeconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeconfirmation',
            name='code_token',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
